### ISSUE TITLE
rotation protein example 1PGB

### ISSUE THREAD

**Issue by Marr575** [pygbe/pygbe#82]
Hello

I would like to run the example of the rotation of the protein 1PGB, I have installed the version of PyGBE of this repository, but checking in your website, the version to rotate the protein is an older version of PyGBE contained in a Figshare repository 

https://figshare.com/articles/Protein_orientation_near_a_charged_surface_using_PyGBe_and_protein_G_B1_D4/1348804/6

how I can made run the run_angle.py program? 

When I run it, sends me error. I think the program is looking for the others python programs but run_angle.py cannot found them because they are not in the correct places. This is the error run_angle.py sends to me.

(base) manuel@manuel-HP-ENVY-dv7-Notebook-PC:~$ sudo python /home/manuel/Descargas/pygbe_master/bem_pycuda/PyGBeOrientation_1PGBsampling_update/run_angle.py /home/manuel/Descargas/pygbe_master/bem_pycuda/PyGBeOrientation_1PGBsampling_update/inputs/1PGB.param /home/manuel/Descargas/pygbe_master/bem_pycuda/PyGBeOrientation_1PGBsampling_update/inputs/1PGBmut_sensor_sigma0.05.config 10 20
[sudo] contraseña para manuel: 

Parameter file:

Precision   double
K           1
Nk          9
K_fine      19
thresold    0.5
BSZ         128
restart     200
tolerance   1e-5
max_iter    1000
P           4
eps         1e-12
NCRIT       300
theta       0.5
GPU         1

Protein file: PyGBeOrientation_1PGBsampling/meshes/1PGBmut_d04
Sensor  file: PyGBeOrientation_1PGBsampling/meshes/sensor_100x10x100_d02
Phi     file: PyGBeOrientation_1PGBsampling/inputs/sensor_100x10x100_d02_-4e-5-4e-5-4e-5-4e-5-4e-5-4e-5.phi0

sh: 1: ./PyGBeOrientation_1PGBsampling/move_protein.py: not found
sh: 1: ./main.py: not found
Traceback (most recent call last):
  File "/home/manuel/Descargas/pygbe_master/bem_pycuda/PyGBeOrientation_1PGBsampling_update/run_angle.py", line 119, in <module>
    N, iterations, Esolv, Esurf, Ecoul, Time, files = scanOutput('output_aux' + name)
  File "/home/manuel/Descargas/pygbe_master/bem_pycuda/PyGBeOrientation_1PGBsampling_update/run_angle.py", line 51, in scanOutput
    return N, iterations, Esolv, Esurf, Ecoul, Time, files
UnboundLocalError: local variable 'N' referenced before assignment

**Comment by ncclementi** [comment]
@Marr575 The `run_angle` script as you said it calls from an older version of `pygbe`. The script to move the protein was updated and you can find it here https://github.com/barbagroup/pygbe/blob/master/preprocessing_tools/move_protein.py
Now, if you would like to run for multiple angles you will need to update the script `run_angle`  in order to use the newer version of pygbe. You can create the folders to run what you need programatically, and then you can run `pygbe` over those folders. This part of the documentation might help you when running, it is not exactly what you are looking for, but you can use it to have an idea on how to run by looping over `example_path_folders`.

**Comment by Marr575** [comment]
Hi again

Does exist a version of run_angle.py in python3? when I try to run it with main.py and move_protein.py give me errors (new versions).

another question which is the function of these functions? cmd_move and cmd_run

cmd_move = './PyGBeOrientation_1PGBsampling/move_protein.py ' + prot_file + ' ' + pqr_file + ' ' + rot_angle + ' ' + tilt_angle + ' ' + name
os.system(cmd_move)

cmd_run = './main.py ' + param_file + ' ' + config_file_moved +' > output_aux' + name
os.system(cmd_run)


Regards

Manuel

**Comment by ncclementi** [comment]
@Marr575 Unfortunately there is not, as I mentioned in the comment above, you'll need to adapt that script to work with the newer version of `pygbe`. It's not only a matter of the python version but also on how you call the program. `move_protein.py` is adapted but that is only a part. If you want `run_angle.py` to run, you need to completely re-write it to work with the lates `pygbe` release. 

cmd_move = './PyGBeOrientation_1PGBsampling/move_protein.py ' + prot_file + ' ' + pqr_file + ' ' + rot_angle + ' ' + tilt_angle + ' ' + name
os.system(cmd_move)

`cmd_move` is a variable, and with `os.system(cmd_move)` is using the built in os library to call the command cmd_move, which calles the `move_protein.py`. If you adapt the version of the script, this line would have to be completely different. The way you call move_protein.py has changed (it is on the documentation of the script).

cmd_run = './main.py ' + param_file + ' ' + config_file_moved +' > output_aux' + name
os.system(cmd_run)

This is a similar case, but here we ar calling a command to run pygbe, in the newer version this is completely different and you'll need to adapt it.

**Comment by Marr575** [comment]
ok, now I'm watching the files move_protein.py and move_protein_helper.py, could you give me two examples of how to use these programs? i want to know how to use them

**Comment by ncclementi** [comment]
@Marr575 The two files you mention are scripts that are use to rotate a protein. `move_protein.py` at the top of the file explains how it works and if you read where we import the functions, all the functions need to work are in `move_prot_helper`. Those functions have descriptive docstrings in that file. 

`move_protein.py` first aligns the dipole moment of the protein with the `y` axis an then it'll rotate in `alpha_y` and `alpha_z` the description of this angles are in the `read_inputs()` in `move_prot_helper`. You need to read the documentation in order to know how it works. 

To run `move_protein.py` you need to pass the arguments as described in the `read_inputs()`:
```
>>> move_protein.py -im mesh_file_you_want_to rotate -ip pqr of the object and so on with all the arguments in the mentioned in the read inputs function` 
```

I hope this helps, although I feel that you might need to study a bit more of python in order to manipulate this scripts. I want to remind you that the issues tool in github is not meant for support on how to use the tools we provide, but to report issues or problems with the software. All extra work regarding modifying scripts or running specific cases that require more coding is your responsibility as a user.
